name: Build and Push dist

on:
  release:
    types: [created]

# 使用并发取消任何当前作业或运行
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:
  action_trigger:
    if:  startsWith(github.ref, 'refs/tags/speaking-exercise-backend/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: get tag info
        uses: MashyChen/tag-parse-action@main
        with:
          githubToken: ${{ secrets.ACTION_TOKEN }}
          type: parse

      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: SeeChange-edu/${{ env.REPOSITORY }}
          token: ${{ secrets.ACTION_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: corretto
          cache: maven

      - name: Maven Build
        run: mvn package -T 1C -D skipTests -D fast

      - name: Build and push Docker image
        run: |
          echo ${{ secrets.TOKEN }} | docker login registry.digitalocean.com -u hilton.lam@asiaalliedgroup.com --password-stdin
          docker build --tag ${{ env.IMAGE }} --file Dockerfile-Self .
          docker push ${{ env.IMAGE }}

      - name: SSH and Run Docker image
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            docker pull ${{ env.IMAGE }}
            if [ "$(docker ps -a --format '{{.Names}}' | grep -c ${{ env.NAME }})" -gt 0 ]; then 
              docker rm -f ${{ env.NAME }}
            fi
            docker run --name ${{ env.NAME }} -d -p ${{ env.OUT_PORT }}:${{ env.PORT }} ${{ env.RUN_ARGS }} --restart unless-stopped ${{ env.IMAGE }}
            docker image prune --force
            docker container prune --force