name: Build and Push dist

on:
  release:
    types: [created]

# 使用并发取消任何当前作业或运行
concurrency:
  group: ${{github.ref}}
  cancel-in-progress: true

jobs:
  action_trigger:
    if:  startsWith(github.ref, 'refs/tags/speaking-exercise-backend/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: get tag info
        uses: MashyChen/tag-parse-action@main
        with:
          githubToken: ${{ secrets.ACTION_TOKEN }}
          type: parse

      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: SeeChange-edu/${{ env.REPOSITORY }}
          token: ${{ secrets.ACTION_TOKEN }}
          ref: ${{ env.BRANCH }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: corretto
          cache: maven

      - name: Maven Build
        run: mvn package -T 1C -D skipTests -D fast